version: '3.8'

services:
  web:
    build: .
    command: python3 /codeusers/manage.py runserver 0.0.0:8000
    volumes:
      - .:/codeusers

    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
   
volumes:
  postgres_data: